# Generated by Django 3.2.13 on 2022-04-22 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='100자 이내. 중복 불가', max_length=100, unique=True, verbose_name='이름')),
                ('category', models.CharField(choices=[('BR', '빵'), ('TO', '토핑'), ('CH', '치즈'), ('SA', '소스')], default='BR', max_length=2, verbose_name='종류')),
                ('stock', models.PositiveIntegerField(default=0, help_text='재고수량', verbose_name='재고')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='가격. 0원 이상', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='가격')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='등록일', verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일', verbose_name='수정일')),
            ],
            options={
                'verbose_name': '샌드위치',
                'verbose_name_plural': '샌드위치 리스트',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='100자 이내. 중복 불가', max_length=100, unique=True, verbose_name='이름')),
                ('description', models.TextField(blank=True, help_text='상세내용. 200자 이내', max_length=200, verbose_name='상세')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='가격. 0원 이상', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='가격')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='등록일', verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일', verbose_name='수정일')),
                ('ingredients', models.ManyToManyField(to='api.Ingredient')),
            ],
            options={
                'verbose_name': '샌드위치',
                'verbose_name_plural': '샌드위치 리스트',
                'ordering': ['-id'],
            },
        ),
    ]
