# Generated by Django 3.2.13 on 2022-04-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='bread',
            field=models.ManyToManyField(to='api.Bread', verbose_name='빵'),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='cheese',
            field=models.ManyToManyField(to='api.Cheese', verbose_name='치즈'),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='sauce',
            field=models.ManyToManyField(to='api.Sauce', verbose_name='소스'),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='topping',
            field=models.ManyToManyField(to='api.Topping', verbose_name='토핑'),
        ),
    ]
